lite:
  version: "0.11.2"
  size: 230kb
  x86url: https://github.com/OneQuick/OneQuick.net/releases/download/bin/OneQuick.Lite.0.11.2.4283.x86.zip
  x64url: https://github.com/OneQuick/OneQuick.net/releases/download/bin/OneQuick.Lite.0.11.2.4284.x64.zip
  launch: OneQuick.exe
  v1note: 预览版
  v2note: 将配置文件位置从LocalAppData改到用户文档目录，自动升级错误的话，请到官网手动升级。
  v3note: 将配置文件位置从LocalAppData改到用户文档目录，自动升级错误的话，请到官网手动升级。
